/**
 * DMCA Takedown Utility
 * Copyright (c) 2024 Ervin Remus Radosavlevici
 * All rights reserved.
 * Contact: radosavlevici.ervin@gmail.com
 * 
 * This file provides utilities for generating DMCA takedown notices.
 */

/**
 * Generate a DMCA takedown notice template
 * @param infringingUrl URL of the infringing content
 * @param originalUrl URL of your original content
 * @returns Formatted DMCA takedown notice
 */
export function generateDMCANotice(infringingUrl: string, originalUrl: string): string {
  const today = new Date().toISOString().split('T')[0];
  
  return `
DMCA Takedown Notice

Date: ${today}

To Whom It May Concern:

I, Ervin Remus Radosavlevici, am the copyright owner of content that is being infringed at:

${infringingUrl}

The original content, for which I own the exclusive copyright, can be found at:

${originalUrl}

This letter is an official notification under the provisions of Section 512(c) of the Digital Millennium Copyright Act ("DMCA") to request the removal of the infringing material.

I have a good faith belief that the use of the material in the manner complained of is not authorized by me, the copyright owner, or the law.

The information in this notification is accurate, and under penalty of perjury, I am the owner of an exclusive right that is allegedly infringed.

I hereby declare that:
1. I am the owner of the exclusive rights to the content described above
2. The content has been copied without my permission
3. The use of my content is not authorized by me, my agent, or the law
4. The information in this notice is accurate
5. I certify under penalty of perjury that I am authorized to act on behalf of the owner of the exclusive rights

I request that you immediately remove or disable access to the infringing material.

Sincerely,

Ervin Remus Radosavlevici
Email: radosavlevici.ervin@gmail.com

`;
}

/**
 * Generate GitHub-specific DMCA takedown notice
 * @param infringingRepo GitHub repository with infringing content
 * @param originalRepo Your original GitHub repository
 * @returns GitHub-formatted DMCA takedown notice
 */
export function generateGitHubDMCANotice(infringingRepo: string, originalRepo: string): string {
  const today = new Date().toISOString().split('T')[0];
  
  return `
DMCA Takedown Notice for GitHub

Date: ${today}

To GitHub, Inc.:

I have read and understand GitHub's Guide to Filing a DMCA Notice.

I, Ervin Remus Radosavlevici, am the copyright owner of content that is being infringed in the following repository:

https://github.com/${infringingRepo}

The original content, for which I own the exclusive copyright, can be found at:

https://github.com/${originalRepo}

The entire repository contains code that infringes my copyright. The unauthorized copying and distribution of my code constitutes copyright infringement under the Copyright Act, 17 U.S.C. §§ 106 and 501.

I have a good faith belief that use of the copyrighted materials described above on the infringing web pages is not authorized by the copyright owner, or its agent, or the law.

I swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner, or am authorized to act on behalf of the owner, of an exclusive right that is allegedly infringed.

I request that GitHub expeditiously remove or disable access to the infringing repository.

Sincerely,

Ervin Remus Radosavlevici
Email: radosavlevici.ervin@gmail.com

`;
}

/**
 * Instructions for filing a DMCA takedown notice
 */
export function getDMCAInstructions(): string {
  return `
DMCA Takedown Instructions

If your code has been stolen or used without permission, follow these steps:

1. Document Evidence:
   - Screenshots of the infringing content
   - Timestamps showing your original creation
   - Git commit history proving your authorship

2. For GitHub repositories:
   - Go to https://github.com/contact/dmca
   - Submit the GitHub DMCA notice generated by this utility
   - Include links to both the infringing and original repositories

3. For other websites:
   - Find the host's DMCA agent (usually in their Terms of Service)
   - Send the general DMCA notice generated by this utility
   - Include URLs to both the infringing and original content

4. Follow up if necessary:
   - Keep records of all communications
   - If the content isn't removed within 1-2 weeks, follow up

For assistance, contact: radosavlevici.ervin@gmail.com
`;
}